[package]
name = "rustdfs-cli"
version = "0.0.0"
edition = "2024"
rust-version = "1.92.0"

[dependencies]
rustdfs-client = { path = "../client" }
clap = { version = "4.5.59", features = ["derive"] }
tokio = { version = "1.47", features = ["macros", "rt-multi-thread", "fs"] }

[[bin]]
name = "rustDFS-client"
path = "src/main.rs"
