# ── build stage ──────────────────────────────────────────────────────────────
FROM rust:1.92.0-trixie AS builder

# protoc is required by tonic-prost-build
RUN apt-get update && apt-get install -y protobuf-compiler && rm -rf /var/lib/apt/lists/*

WORKDIR /build
COPY . .
RUN cargo build --release

# ── runtime stage ─────────────────────────────────────────────────────────────
FROM gcc:latest

RUN apt-get update \
    && apt-get install -y ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /root/read

COPY --from=builder /build/target/release/librustdfs_client.so /usr/local/lib/
COPY example/c_basic/client.c /root/
COPY example/c_basic/rustdfs.h /root/
COPY example/files/ /root/files/
RUN gcc -o /root/client /root/client.c -L/usr/local/lib -lrustdfs_client -I/root
RUN ldconfig

CMD ["/root/client"]
